//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPGridActionParams
    {
        public int ID { get; set; }
        public int GridActionId { get; set; }
        public string ParamName { get; set; }
        public bool ParamHasFixedValue { get; set; }
        public string ParamValueField { get; set; }
    
        public virtual APPGridActions APPGridActions { get; set; }
    }
}
