//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppNotifications
    {
        public int IdNotificacion { get; set; }
        public int IdJobtrackRecepcion { get; set; }
        public string Mensaje { get; set; }
        public bool Leido { get; set; }
        public System.DateTime Fecha { get; set; }
    }
}
