//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPWebPrintDirectFiles
    {
        public int RegId { get; set; }
        public string JobtrackName { get; set; }
        public string FileName { get; set; }
        public System.DateTime FechaReg { get; set; }
        public string Status { get; set; }
        public bool Impreso { get; set; }
    }
}
