//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_METRICS_VIEW_REL_RECURSOS_ACTIVIDADES
    {
        public string NumOrdem { get; set; }
        public Nullable<int> IdAtiv { get; set; }
        public int IdAtivProcess { get; set; }
        public string CodAtiv { get; set; }
        public string CodRecurso { get; set; }
        public Nullable<double> BONS { get; set; }
    }
}
