//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_METRICS_TRAE_PRODUCCION_TOTAL_ULT30_DIAS
    {
        public string NUMORDEM { get; set; }
        public Nullable<int> PRODUCCION_MTS { get; set; }
        public double PRODUCCION_KGS { get; set; }
    }
}
