//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_METRICS_OP_ACTIVIDADES
    {
        public string NumOrdem { get; set; }
        public string TituloOP { get; set; }
        public string NombreCliente { get; set; }
        public string CodEstrutura { get; set; }
        public string Descricao { get; set; }
        public string CodAtiv { get; set; }
        public string Processo { get; set; }
        public Nullable<double> GramajeFInal { get; set; }
        public string CodGrupoProd { get; set; }
        public Nullable<double> QtdPlanejadaMT { get; set; }
        public Nullable<decimal> QtdPlanejadaKG { get; set; }
        public Nullable<double> QtdProduzidoMT { get; set; }
        public Nullable<double> ScrapProductionMT { get; set; }
        public Nullable<double> ScrapMakeReadyMT { get; set; }
        public Nullable<decimal> QtdProduzidoKG { get; set; }
        public Nullable<decimal> ScrapProductionKG { get; set; }
        public Nullable<decimal> ScrapMakeReadyKG { get; set; }
        public Nullable<double> FatorKG { get; set; }
        public Nullable<double> FatorMT { get; set; }
        public Nullable<double> FatorUN { get; set; }
        public string Unidade { get; set; }
        public string SeqProcesso { get; set; }
        public Nullable<int> SeqDefault { get; set; }
        public double FatorComprimentoProducao { get; set; }
        public double FatorPesoProducao { get; set; }
        public string USR_DistaeTacosmm { get; set; }
        public string USR_DistaeTacos1m { get; set; }
    }
}
