//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_METRICSPROD_DATOSPESO_X_ATIV
    {
        public string NumOrdem { get; set; }
        public int idativ { get; set; }
        public string Idprocesso { get; set; }
        public string CodAtiv { get; set; }
        public Nullable<double> fatorpeso { get; set; }
        public Nullable<double> FatorComprimento { get; set; }
        public Nullable<double> FatorUnidade { get; set; }
    }
}
