//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_PSSSCRAP_TOTAL_X_ORDEN_X_ACTIVIDAD
    {
        public int NUMOP { get; set; }
        public string Actividad { get; set; }
        public string Recurso { get; set; }
        public Nullable<decimal> PESO { get; set; }
    }
}
