//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_PSSSCRAP_TOTAL_SCRAP_X_OP
    {
        public int NumOP { get; set; }
        public Nullable<decimal> KGSCRAP { get; set; }
        public Nullable<decimal> KGSCRAP_CONSIDERADO_PRD { get; set; }
    }
}
