//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CV_SCRAP_PORCENTAJE_TOTAL_X_OP
    {
        public string NUMORDEM { get; set; }
        public Nullable<int> IdAtiv { get; set; }
        public string DescripcionOP { get; set; }
        public string CodAtiv { get; set; }
        public Nullable<double> QtdProduzidaMts { get; set; }
        public Nullable<double> QtdProduzidaKg { get; set; }
        public decimal KGTOTALSCRAP { get; set; }
        public Nullable<double> porcentajescrap { get; set; }
    }
}
