//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPModulosResponsables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GPModulosResponsables()
        {
            this.GPProductos = new HashSet<GPProductos>();
        }
    
        public int IdModuloProducto { get; set; }
        public int IdResponsable { get; set; }
        public int Id { get; set; }
    
        public virtual GPModulosProductos GPModulosProductos { get; set; }
        public virtual GPResponsables GPResponsables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPProductos> GPProductos { get; set; }
    }
}
