//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPPerfilesPrePrensa
    {
        public int IdPerfilPrePrensa { get; set; }
        public string Descripcion { get; set; }
        public int IdImpresora { get; set; }
        public int IdProveedor { get; set; }
        public int IdTipoMaterial { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual GPImpresoras GPImpresoras { get; set; }
        public virtual GPTipoMaterial GPTipoMaterial { get; set; }
    }
}
