//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPPGruposEmpaque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GPPGruposEmpaque()
        {
            this.GPProductos = new HashSet<GPProductos>();
        }
    
        public int IDGrupoEmpaque { get; set; }
        public string Descripcion { get; set; }
        public bool EtiquetaInterna { get; set; }
        public int TipoEtiquetaInterna { get; set; }
        public bool EtiquetaExterna { get; set; }
        public int TipoEtiquetaExterna { get; set; }
        public int TipoEtiquetaPallet { get; set; }
        public bool Habilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPProductos> GPProductos { get; set; }
    }
}
