//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPProductoSeguimientoMail
    {
        public string CodProducto { get; set; }
        public System.DateTime DailyLastRefreshDate { get; set; }
        public bool DailyRefreshExecuted { get; set; }
        public bool MailSinPreprensaSent { get; set; }
        public System.DateTime MailSinPreprensaSentDatetime { get; set; }
        public bool MailNuevoCilindroSent { get; set; }
        public System.DateTime MailNuevoCilindroSentDatetime { get; set; }
    }
}
