//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPPTiposEtiquetas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GPPTiposEtiquetas()
        {
            this.GPPGruposEmpaque = new HashSet<GPPGruposEmpaque>();
            this.GPPGruposEmpaque1 = new HashSet<GPPGruposEmpaque>();
            this.GPPGruposEmpaque2 = new HashSet<GPPGruposEmpaque>();
        }
    
        public int IdEtiqueta { get; set; }
        public string Descripcion { get; set; }
        public bool Habilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPPGruposEmpaque> GPPGruposEmpaque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPPGruposEmpaque> GPPGruposEmpaque1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GPPGruposEmpaque> GPPGruposEmpaque2 { get; set; }
    }
}
