//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metrics_Indicadores_Scrap_OP_Cerradas
    {
        public string CODRECURSO { get; set; }
        public Nullable<int> IDArea { get; set; }
        public Nullable<System.DateTime> DTPRODUCAO { get; set; }
        public Nullable<int> PRODUCCION_MTS { get; set; }
        public Nullable<double> PRODUCCION_KGS { get; set; }
        public decimal SCRAPKG { get; set; }
        public Nullable<decimal> INCIDENCIA { get; set; }
    }
}
