//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metrics_Indicadores_Historico_Totales_OP
    {
        public string Estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> PRODUCCION_MTS { get; set; }
        public Nullable<double> PRODUCCION_KGS { get; set; }
        public Nullable<double> SCRAP_KGS { get; set; }
        public Nullable<double> PORCENTAJE { get; set; }
        public Nullable<double> SCRAP_CONSIDERADO_PRD { get; set; }
        public Nullable<double> SCRAP_NO_CONSIDERADO_PRD { get; set; }
    }
}
