//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LAFScrapEntities : DbContext
    {
        public LAFScrapEntities()
            : base("name=LAFScrapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<APPGridActionParams> APPGridActionParams { get; set; }
        public virtual DbSet<APPGridActions> APPGridActions { get; set; }
        public virtual DbSet<APPMenu> APPMenu { get; set; }
        public virtual DbSet<APPParametros> APPParametros { get; set; }
        public virtual DbSet<APPWebPrintDirectFiles> APPWebPrintDirectFiles { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<GPEstadosPrePrensa> GPEstadosPrePrensa { get; set; }
        public virtual DbSet<GPEstadosProductos> GPEstadosProductos { get; set; }
        public virtual DbSet<GPImpresoras> GPImpresoras { get; set; }
        public virtual DbSet<GPModulosProductos> GPModulosProductos { get; set; }
        public virtual DbSet<GPModulosResponsables> GPModulosResponsables { get; set; }
        public virtual DbSet<GPPerfilesPrePrensa> GPPerfilesPrePrensa { get; set; }
        public virtual DbSet<GPProductos> GPProductos { get; set; }
        public virtual DbSet<GPResponsables> GPResponsables { get; set; }
        public virtual DbSet<GPTipoMaterial> GPTipoMaterial { get; set; }
        public virtual DbSet<GPTrabajosCilindros> GPTrabajosCilindros { get; set; }
        public virtual DbSet<Metrics_Indicadores_Historico_Totales_OP> Metrics_Indicadores_Historico_Totales_OP { get; set; }
        public virtual DbSet<Metrics_Recursos_Habilitados> Metrics_Recursos_Habilitados { get; set; }
        public virtual DbSet<PSS_CIERRE_MENSUAL_HIST> PSS_CIERRE_MENSUAL_HIST { get; set; }
        public virtual DbSet<PSSActividades> PSSActividades { get; set; }
        public virtual DbSet<PSSAreas> PSSAreas { get; set; }
        public virtual DbSet<PSSEtiquetas> PSSEtiquetas { get; set; }
        public virtual DbSet<PSSJobTrack> PSSJobTrack { get; set; }
        public virtual DbSet<PSSJobtrackModulos> PSSJobtrackModulos { get; set; }
        public virtual DbSet<PSSMaquinas> PSSMaquinas { get; set; }
        public virtual DbSet<PSSMotivosScrap> PSSMotivosScrap { get; set; }
        public virtual DbSet<PSSMotivosScrapObjetivos> PSSMotivosScrapObjetivos { get; set; }
        public virtual DbSet<PSSMotivosScrapVinculos> PSSMotivosScrapVinculos { get; set; }
        public virtual DbSet<PSSOperadores> PSSOperadores { get; set; }
        public virtual DbSet<PSSOrigenesScrap> PSSOrigenesScrap { get; set; }
        public virtual DbSet<PSSProductos> PSSProductos { get; set; }
        public virtual DbSet<PSSRomaneo> PSSRomaneo { get; set; }
        public virtual DbSet<PSSRomaneoItems> PSSRomaneoItems { get; set; }
        public virtual DbSet<PSSScrap> PSSScrap { get; set; }
        public virtual DbSet<PSSScrapValoresPorPeriodoMensual> PSSScrapValoresPorPeriodoMensual { get; set; }
        public virtual DbSet<PSSTabacoBobinas> PSSTabacoBobinas { get; set; }
        public virtual DbSet<PSSTabacoPallets> PSSTabacoPallets { get; set; }
        public virtual DbSet<PSSTiposMaterial> PSSTiposMaterial { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trazabilidad> Trazabilidad { get; set; }
        public virtual DbSet<Trazabilidad_Det> Trazabilidad_Det { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Metrics_Indicadores_Scrap> Metrics_Indicadores_Scrap { get; set; }
        public virtual DbSet<Metrics_Indicadores_Scrap_Laminadoras> Metrics_Indicadores_Scrap_Laminadoras { get; set; }
        public virtual DbSet<Metrics_Indicadores_Scrap_OP_Cerradas> Metrics_Indicadores_Scrap_OP_Cerradas { get; set; }
        public virtual DbSet<PSSJobtracksActivePallets> PSSJobtracksActivePallets { get; set; }
        public virtual DbSet<UserClaim> UserClaim { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<VIEW_USR_M3_ORDATIVIDADES_AC_test> VIEW_USR_M3_ORDATIVIDADES_AC_test { get; set; }
        public virtual DbSet<CV_LLENA_DATOS_LAMINADORAS> CV_LLENA_DATOS_LAMINADORAS { get; set; }
        public virtual DbSet<CV_LLENA_DATOS_LAMINADORAS_OP_CERRADAS> CV_LLENA_DATOS_LAMINADORAS_OP_CERRADAS { get; set; }
        public virtual DbSet<CV_METRICS_MAX_CANT_UNIDADES_X_ORDEN> CV_METRICS_MAX_CANT_UNIDADES_X_ORDEN { get; set; }
        public virtual DbSet<CV_METRICS_OP_ACTIVIDADES> CV_METRICS_OP_ACTIVIDADES { get; set; }
        public virtual DbSet<CV_METRICS_TRAE_PRODUCCION_TOTAL_ULT30_DIAS> CV_METRICS_TRAE_PRODUCCION_TOTAL_ULT30_DIAS { get; set; }
        public virtual DbSet<CV_METRICS_TRAE_PRODUCCION_TOTAL_ULT30_DIAS_CERRADAS> CV_METRICS_TRAE_PRODUCCION_TOTAL_ULT30_DIAS_CERRADAS { get; set; }
        public virtual DbSet<CV_METRICS_VIEW_REL_RECURSOS_ACTIVIDADES> CV_METRICS_VIEW_REL_RECURSOS_ACTIVIDADES { get; set; }
        public virtual DbSet<CV_METRICSPROD_DATOSPESO_X_ATIV> CV_METRICSPROD_DATOSPESO_X_ATIV { get; set; }
        public virtual DbSet<CV_METRICSPROD_LISTAR_MAXIDATIV> CV_METRICSPROD_LISTAR_MAXIDATIV { get; set; }
        public virtual DbSet<CV_PSSSCRAP_PESOS_TOTALES_X_MAQUINA_IMPUTE_X_FECHA> CV_PSSSCRAP_PESOS_TOTALES_X_MAQUINA_IMPUTE_X_FECHA { get; set; }
        public virtual DbSet<CV_PSSSCRAP_PESOS_TOTALES_X_MAQUINA_X_FECHA> CV_PSSSCRAP_PESOS_TOTALES_X_MAQUINA_X_FECHA { get; set; }
        public virtual DbSet<CV_PSSSCRAP_TOTAL_SCRAP_X_OP> CV_PSSSCRAP_TOTAL_SCRAP_X_OP { get; set; }
        public virtual DbSet<CV_PSSSCRAP_TOTAL_SCRAP_X_OP_ULT30DIAS> CV_PSSSCRAP_TOTAL_SCRAP_X_OP_ULT30DIAS { get; set; }
        public virtual DbSet<CV_PSSSCRAP_TOTAL_SCRAP_X_OP_ULT30DIAS_CERRADAS> CV_PSSSCRAP_TOTAL_SCRAP_X_OP_ULT30DIAS_CERRADAS { get; set; }
        public virtual DbSet<CV_PSSSCRAP_TOTAL_X_ORDEN_X_ACTIVIDAD> CV_PSSSCRAP_TOTAL_X_ORDEN_X_ACTIVIDAD { get; set; }
        public virtual DbSet<CV_SCRAP_PORCENTAJE_TOTAL_X_OP> CV_SCRAP_PORCENTAJE_TOTAL_X_OP { get; set; }
        public virtual DbSet<V_SCRAP_MOTIVOS_TBL1> V_SCRAP_MOTIVOS_TBL1 { get; set; }
        public virtual DbSet<V_SCRAP_MOTIVOS_TBL1_AÑO_ANT> V_SCRAP_MOTIVOS_TBL1_AÑO_ANT { get; set; }
        public virtual DbSet<V_SCRAP_NO_CONSIDERADO_TBL1> V_SCRAP_NO_CONSIDERADO_TBL1 { get; set; }
        public virtual DbSet<V_SCRAP_NO_CONSIDERADO_TBL1_AÑO_ANT> V_SCRAP_NO_CONSIDERADO_TBL1_AÑO_ANT { get; set; }
        public virtual DbSet<V_TONS_PRODUCIDAS_TBL1> V_TONS_PRODUCIDAS_TBL1 { get; set; }
        public virtual DbSet<V_TONS_PRODUCIDAS_TBL1_AÑO_ANT> V_TONS_PRODUCIDAS_TBL1_AÑO_ANT { get; set; }
    
        public virtual int CPS_TRAZABILIDAD_INSERT(Nullable<int> nROOP, Nullable<int> tIPO, Nullable<int> lEGAJO, Nullable<int> cANT_GENERADA, Nullable<int> dESDE, Nullable<int> hASTA, Nullable<int> cANT_ELEMENTOS, Nullable<double> mETROS, Nullable<bool> mUESTRA)
        {
            var nROOPParameter = nROOP.HasValue ?
                new ObjectParameter("NROOP", nROOP) :
                new ObjectParameter("NROOP", typeof(int));
    
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(int));
    
            var lEGAJOParameter = lEGAJO.HasValue ?
                new ObjectParameter("LEGAJO", lEGAJO) :
                new ObjectParameter("LEGAJO", typeof(int));
    
            var cANT_GENERADAParameter = cANT_GENERADA.HasValue ?
                new ObjectParameter("CANT_GENERADA", cANT_GENERADA) :
                new ObjectParameter("CANT_GENERADA", typeof(int));
    
            var dESDEParameter = dESDE.HasValue ?
                new ObjectParameter("DESDE", dESDE) :
                new ObjectParameter("DESDE", typeof(int));
    
            var hASTAParameter = hASTA.HasValue ?
                new ObjectParameter("HASTA", hASTA) :
                new ObjectParameter("HASTA", typeof(int));
    
            var cANT_ELEMENTOSParameter = cANT_ELEMENTOS.HasValue ?
                new ObjectParameter("CANT_ELEMENTOS", cANT_ELEMENTOS) :
                new ObjectParameter("CANT_ELEMENTOS", typeof(int));
    
            var mETROSParameter = mETROS.HasValue ?
                new ObjectParameter("METROS", mETROS) :
                new ObjectParameter("METROS", typeof(double));
    
            var mUESTRAParameter = mUESTRA.HasValue ?
                new ObjectParameter("MUESTRA", mUESTRA) :
                new ObjectParameter("MUESTRA", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CPS_TRAZABILIDAD_INSERT", nROOPParameter, tIPOParameter, lEGAJOParameter, cANT_GENERADAParameter, dESDEParameter, hASTAParameter, cANT_ELEMENTOSParameter, mETROSParameter, mUESTRAParameter);
        }
    
        public virtual int CSP_APP_WEBPRINTDIRECTFILES_INSERT(string pJOBTRACKNAME, string pFILENAME)
        {
            var pJOBTRACKNAMEParameter = pJOBTRACKNAME != null ?
                new ObjectParameter("PJOBTRACKNAME", pJOBTRACKNAME) :
                new ObjectParameter("PJOBTRACKNAME", typeof(string));
    
            var pFILENAMEParameter = pFILENAME != null ?
                new ObjectParameter("PFILENAME", pFILENAME) :
                new ObjectParameter("PFILENAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_APP_WEBPRINTDIRECTFILES_INSERT", pJOBTRACKNAMEParameter, pFILENAMEParameter);
        }
    
        public virtual ObjectResult<CSP_APPGRIDACTIONPARAMS_X_ACTIONID_Result> CSP_APPGRIDACTIONPARAMS_X_ACTIONID(Nullable<int> pACTIONID)
        {
            var pACTIONIDParameter = pACTIONID.HasValue ?
                new ObjectParameter("PACTIONID", pACTIONID) :
                new ObjectParameter("PACTIONID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_APPGRIDACTIONPARAMS_X_ACTIONID_Result>("CSP_APPGRIDACTIONPARAMS_X_ACTIONID", pACTIONIDParameter);
        }
    
        public virtual ObjectResult<CSP_APPGRIDACTIONS_X_GRIDOBJECTNAME_Result> CSP_APPGRIDACTIONS_X_GRIDOBJECTNAME(string pGRIDOBJNAME)
        {
            var pGRIDOBJNAMEParameter = pGRIDOBJNAME != null ?
                new ObjectParameter("PGRIDOBJNAME", pGRIDOBJNAME) :
                new ObjectParameter("PGRIDOBJNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_APPGRIDACTIONS_X_GRIDOBJECTNAME_Result>("CSP_APPGRIDACTIONS_X_GRIDOBJECTNAME", pGRIDOBJNAMEParameter);
        }
    
        public virtual ObjectResult<CSP_APPMENU_LISTAR_Result> CSP_APPMENU_LISTAR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_APPMENU_LISTAR_Result>("CSP_APPMENU_LISTAR");
        }
    
        public virtual ObjectResult<CSP_APPPARAMS_GET_VALUE_Result> CSP_APPPARAMS_GET_VALUE(string p_IDPARAM)
        {
            var p_IDPARAMParameter = p_IDPARAM != null ?
                new ObjectParameter("P_IDPARAM", p_IDPARAM) :
                new ObjectParameter("P_IDPARAM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_APPPARAMS_GET_VALUE_Result>("CSP_APPPARAMS_GET_VALUE", p_IDPARAMParameter);
        }
    
        public virtual ObjectResult<CSP_CHEQUEA_PALLET_GENERADO_Result> CSP_CHEQUEA_PALLET_GENERADO(string pNROOF, Nullable<int> pRNOPALLET)
        {
            var pNROOFParameter = pNROOF != null ?
                new ObjectParameter("PNROOF", pNROOF) :
                new ObjectParameter("PNROOF", typeof(string));
    
            var pRNOPALLETParameter = pRNOPALLET.HasValue ?
                new ObjectParameter("PRNOPALLET", pRNOPALLET) :
                new ObjectParameter("PRNOPALLET", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_CHEQUEA_PALLET_GENERADO_Result>("CSP_CHEQUEA_PALLET_GENERADO", pNROOFParameter, pRNOPALLETParameter);
        }
    
        public virtual ObjectResult<CSP_DASHBOARD_SLA_PRODUCTOS_Result> CSP_DASHBOARD_SLA_PRODUCTOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_DASHBOARD_SLA_PRODUCTOS_Result>("CSP_DASHBOARD_SLA_PRODUCTOS");
        }
    
        public virtual ObjectResult<CSP_DASHBOARD_SLA_PRODUCTOS_TOTAL_Result> CSP_DASHBOARD_SLA_PRODUCTOS_TOTAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_DASHBOARD_SLA_PRODUCTOS_TOTAL_Result>("CSP_DASHBOARD_SLA_PRODUCTOS_TOTAL");
        }
    
        public virtual int CSP_GET_ALL_TREE_NODES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_GET_ALL_TREE_NODES");
        }
    
        public virtual ObjectResult<CSP_GET_CUSTOMER_OC_BY_NUMOF_Result> CSP_GET_CUSTOMER_OC_BY_NUMOF(string nUMOF)
        {
            var nUMOFParameter = nUMOF != null ?
                new ObjectParameter("NUMOF", nUMOF) :
                new ObjectParameter("NUMOF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GET_CUSTOMER_OC_BY_NUMOF_Result>("CSP_GET_CUSTOMER_OC_BY_NUMOF", nUMOFParameter);
        }
    
        public virtual ObjectResult<CSP_GET_MAQUINAS_X_AREA_Result> CSP_GET_MAQUINAS_X_AREA(Nullable<int> pIDAREA)
        {
            var pIDAREAParameter = pIDAREA.HasValue ?
                new ObjectParameter("PIDAREA", pIDAREA) :
                new ObjectParameter("PIDAREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GET_MAQUINAS_X_AREA_Result>("CSP_GET_MAQUINAS_X_AREA", pIDAREAParameter);
        }
    
        public virtual ObjectResult<CSP_GET_ORIGENESSCRAP_X_MAQUINA_Result> CSP_GET_ORIGENESSCRAP_X_MAQUINA(Nullable<int> pIDMAQ)
        {
            var pIDMAQParameter = pIDMAQ.HasValue ?
                new ObjectParameter("PIDMAQ", pIDMAQ) :
                new ObjectParameter("PIDMAQ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GET_ORIGENESSCRAP_X_MAQUINA_Result>("CSP_GET_ORIGENESSCRAP_X_MAQUINA", pIDMAQParameter);
        }
    
        public virtual ObjectResult<CSP_GET_SEGUIMIENTO_PRODUCTO_X_CODIGO_Result> CSP_GET_SEGUIMIENTO_PRODUCTO_X_CODIGO(string cOD_PRODUCTO)
        {
            var cOD_PRODUCTOParameter = cOD_PRODUCTO != null ?
                new ObjectParameter("COD_PRODUCTO", cOD_PRODUCTO) :
                new ObjectParameter("COD_PRODUCTO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GET_SEGUIMIENTO_PRODUCTO_X_CODIGO_Result>("CSP_GET_SEGUIMIENTO_PRODUCTO_X_CODIGO", cOD_PRODUCTOParameter);
        }
    
        public virtual ObjectResult<CSP_GET_TIPOSMATERIAL_X_MAQUINA_Result> CSP_GET_TIPOSMATERIAL_X_MAQUINA(Nullable<int> pIDMAQ)
        {
            var pIDMAQParameter = pIDMAQ.HasValue ?
                new ObjectParameter("PIDMAQ", pIDMAQ) :
                new ObjectParameter("PIDMAQ", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GET_TIPOSMATERIAL_X_MAQUINA_Result>("CSP_GET_TIPOSMATERIAL_X_MAQUINA", pIDMAQParameter);
        }
    
        public virtual ObjectResult<CSP_GET_TIPOSMATERIAL_X_MAQUINA_X_ORIGENSCRAP_Result> CSP_GET_TIPOSMATERIAL_X_MAQUINA_X_ORIGENSCRAP(Nullable<int> pIDMAQ, Nullable<int> pIDORIGEN)
        {
            var pIDMAQParameter = pIDMAQ.HasValue ?
                new ObjectParameter("PIDMAQ", pIDMAQ) :
                new ObjectParameter("PIDMAQ", typeof(int));
    
            var pIDORIGENParameter = pIDORIGEN.HasValue ?
                new ObjectParameter("PIDORIGEN", pIDORIGEN) :
                new ObjectParameter("PIDORIGEN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GET_TIPOSMATERIAL_X_MAQUINA_X_ORIGENSCRAP_Result>("CSP_GET_TIPOSMATERIAL_X_MAQUINA_X_ORIGENSCRAP", pIDMAQParameter, pIDORIGENParameter);
        }
    
        public virtual ObjectResult<CSP_GPPRODUCTOS_EXCEL_EXPORT_Result> CSP_GPPRODUCTOS_EXCEL_EXPORT(Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_FIN, Nullable<int> eSTADO)
        {
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            var eSTADOParameter = eSTADO.HasValue ?
                new ObjectParameter("ESTADO", eSTADO) :
                new ObjectParameter("ESTADO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GPPRODUCTOS_EXCEL_EXPORT_Result>("CSP_GPPRODUCTOS_EXCEL_EXPORT", fECHA_INICIOParameter, fECHA_FINParameter, eSTADOParameter);
        }
    
        public virtual ObjectResult<CSP_GPPRODUCTOS_EXCEL_GRABADOS_EXPORT_Result> CSP_GPPRODUCTOS_EXCEL_GRABADOS_EXPORT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GPPRODUCTOS_EXCEL_GRABADOS_EXPORT_Result>("CSP_GPPRODUCTOS_EXCEL_GRABADOS_EXPORT");
        }
    
        public virtual int CSP_GPPRODUCTOS_INSERT_NEW_PRODUCTS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_GPPRODUCTOS_INSERT_NEW_PRODUCTS");
        }
    
        public virtual ObjectResult<CSP_GPPRODUCTOS_KPI_INGENIERIA_GENERAL_Result> CSP_GPPRODUCTOS_KPI_INGENIERIA_GENERAL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GPPRODUCTOS_KPI_INGENIERIA_GENERAL_Result>("CSP_GPPRODUCTOS_KPI_INGENIERIA_GENERAL");
        }
    
        public virtual ObjectResult<CSP_GPPRODUCTOS_KPI_PREPRENSA_DIAS_ENVIOET_Result> CSP_GPPRODUCTOS_KPI_PREPRENSA_DIAS_ENVIOET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GPPRODUCTOS_KPI_PREPRENSA_DIAS_ENVIOET_Result>("CSP_GPPRODUCTOS_KPI_PREPRENSA_DIAS_ENVIOET");
        }
    
        public virtual ObjectResult<CSP_GPPRODUCTOS_KPI_PREPRENSA_LIBGRABADOVSRECEPCIONHERRAMENTAL_X_PROVEEDOR_Result> CSP_GPPRODUCTOS_KPI_PREPRENSA_LIBGRABADOVSRECEPCIONHERRAMENTAL_X_PROVEEDOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GPPRODUCTOS_KPI_PREPRENSA_LIBGRABADOVSRECEPCIONHERRAMENTAL_X_PROVEEDOR_Result>("CSP_GPPRODUCTOS_KPI_PREPRENSA_LIBGRABADOVSRECEPCIONHERRAMENTAL_X_PROVEEDOR");
        }
    
        public virtual ObjectResult<CSP_GPPRODUCTOS_KPI_PREPRENSA_LIBGRABADOVSRECEPCIONHERRAMENTAL_X_TIPOIMPRESORA_Result> CSP_GPPRODUCTOS_KPI_PREPRENSA_LIBGRABADOVSRECEPCIONHERRAMENTAL_X_TIPOIMPRESORA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GPPRODUCTOS_KPI_PREPRENSA_LIBGRABADOVSRECEPCIONHERRAMENTAL_X_TIPOIMPRESORA_Result>("CSP_GPPRODUCTOS_KPI_PREPRENSA_LIBGRABADOVSRECEPCIONHERRAMENTAL_X_TIPOIMPRESORA");
        }
    
        public virtual ObjectResult<CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_PROVEEDOR_Result> CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_PROVEEDOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_PROVEEDOR_Result>("CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_PROVEEDOR");
        }
    
        public virtual ObjectResult<CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_RESPONSABLE_Result> CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_RESPONSABLE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_RESPONSABLE_Result>("CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_RESPONSABLE");
        }
    
        public virtual ObjectResult<CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_TIPOIMPRESORA_Result> CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_TIPOIMPRESORA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_TIPOIMPRESORA_Result>("CSP_GPPRODUCTOS_KPI_PREPRENSA_QTY_X_TIPOIMPRESORA");
        }
    
        public virtual int CSP_GPPRODUCTOS_REFRESH_PRODUCT_INFORMATION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_GPPRODUCTOS_REFRESH_PRODUCT_INFORMATION");
        }
    
        public virtual ObjectResult<CSP_GPTRABAJOSCILINDROS_EXCEL_EXPORT_Result> CSP_GPTRABAJOSCILINDROS_EXCEL_EXPORT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_GPTRABAJOSCILINDROS_EXCEL_EXPORT_Result>("CSP_GPTRABAJOSCILINDROS_EXCEL_EXPORT");
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> CSP_HISTORIZA_CIERRE_MES_OP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("CSP_HISTORIZA_CIERRE_MES_OP");
        }
    
        public virtual ObjectResult<CSP_INDICADOR_TOTAL_SCRAP_X_OP_Result> CSP_INDICADOR_TOTAL_SCRAP_X_OP(string nUMORDEM)
        {
            var nUMORDEMParameter = nUMORDEM != null ?
                new ObjectParameter("NUMORDEM", nUMORDEM) :
                new ObjectParameter("NUMORDEM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_INDICADOR_TOTAL_SCRAP_X_OP_Result>("CSP_INDICADOR_TOTAL_SCRAP_X_OP", nUMORDEMParameter);
        }
    
        public virtual int CSP_INDICADORES_IMPRESORAS_ULT7_DIAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_INDICADORES_IMPRESORAS_ULT7_DIAS");
        }
    
        public virtual ObjectResult<CSP_INDICADORES_IMPRESORAS_X_MES_Result> CSP_INDICADORES_IMPRESORAS_X_MES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_INDICADORES_IMPRESORAS_X_MES_Result>("CSP_INDICADORES_IMPRESORAS_X_MES");
        }
    
        public virtual ObjectResult<CSP_INDICADORES_LAMINADORAS_ULT7_DIAS_Result> CSP_INDICADORES_LAMINADORAS_ULT7_DIAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_INDICADORES_LAMINADORAS_ULT7_DIAS_Result>("CSP_INDICADORES_LAMINADORAS_ULT7_DIAS");
        }
    
        public virtual ObjectResult<CSP_INDICADORES_LAMINADORAS_X_MES_Result> CSP_INDICADORES_LAMINADORAS_X_MES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_INDICADORES_LAMINADORAS_X_MES_Result>("CSP_INDICADORES_LAMINADORAS_X_MES");
        }
    
        public virtual ObjectResult<CSP_INDICADORES_PORCENTAJE_POR_AREA_Result> CSP_INDICADORES_PORCENTAJE_POR_AREA(Nullable<int> pIDAREA)
        {
            var pIDAREAParameter = pIDAREA.HasValue ?
                new ObjectParameter("PIDAREA", pIDAREA) :
                new ObjectParameter("PIDAREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_INDICADORES_PORCENTAJE_POR_AREA_Result>("CSP_INDICADORES_PORCENTAJE_POR_AREA", pIDAREAParameter);
        }
    
        public virtual ObjectResult<CSP_INDICADORES_PORCENTAJE_TOTAL_PLANTA_Result> CSP_INDICADORES_PORCENTAJE_TOTAL_PLANTA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_INDICADORES_PORCENTAJE_TOTAL_PLANTA_Result>("CSP_INDICADORES_PORCENTAJE_TOTAL_PLANTA");
        }
    
        public virtual ObjectResult<CSP_INDICADORES_PORCENTAJE_TOTAL_PLANTA_OP_CERRADAS_Result> CSP_INDICADORES_PORCENTAJE_TOTAL_PLANTA_OP_CERRADAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_INDICADORES_PORCENTAJE_TOTAL_PLANTA_OP_CERRADAS_Result>("CSP_INDICADORES_PORCENTAJE_TOTAL_PLANTA_OP_CERRADAS");
        }
    
        public virtual ObjectResult<CSP_INDICADORES_SCRAP_PRODUCCION_Result> CSP_INDICADORES_SCRAP_PRODUCCION()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_INDICADORES_SCRAP_PRODUCCION_Result>("CSP_INDICADORES_SCRAP_PRODUCCION");
        }
    
        public virtual ObjectResult<CSP_INDICADORES_TOTALES_OP_X_MES_Result> CSP_INDICADORES_TOTALES_OP_X_MES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_INDICADORES_TOTALES_OP_X_MES_Result>("CSP_INDICADORES_TOTALES_OP_X_MES");
        }
    
        public virtual ObjectResult<CSP_LISTAR_REGISTROS_SCRAP_X_AREA_Result> CSP_LISTAR_REGISTROS_SCRAP_X_AREA(Nullable<int> pAREA)
        {
            var pAREAParameter = pAREA.HasValue ?
                new ObjectParameter("PAREA", pAREA) :
                new ObjectParameter("PAREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_LISTAR_REGISTROS_SCRAP_X_AREA_Result>("CSP_LISTAR_REGISTROS_SCRAP_X_AREA", pAREAParameter);
        }
    
        public virtual ObjectResult<CSP_LISTAR_SEGUMIENTO_PRODUCTO_Result> CSP_LISTAR_SEGUMIENTO_PRODUCTO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_LISTAR_SEGUMIENTO_PRODUCTO_Result>("CSP_LISTAR_SEGUMIENTO_PRODUCTO");
        }
    
        public virtual int CSP_LLENA_METRICS_INDICADORES_SCRAP_DIA_ANTERIOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_LLENA_METRICS_INDICADORES_SCRAP_DIA_ANTERIOR");
        }
    
        public virtual int CSP_LLENA_METRICS_INDICADORES_SCRAP_OP_CERRADAS_DIA_ANTERIOR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_LLENA_METRICS_INDICADORES_SCRAP_OP_CERRADAS_DIA_ANTERIOR");
        }
    
        public virtual int CSP_METRICS_JOB_LLENA_TABLA_HISTORICO_OP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_METRICS_JOB_LLENA_TABLA_HISTORICO_OP");
        }
    
        public virtual int CSP_METRICS_ORDENDESPRODUCCION_GETALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_METRICS_ORDENDESPRODUCCION_GETALL");
        }
    
        public virtual int CSP_METRICS_ORDENDESPRODUCCION_GETALL_ABIERTAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_METRICS_ORDENDESPRODUCCION_GETALL_ABIERTAS");
        }
    
        public virtual ObjectResult<CSP_METRICS_ORDENDESPRODUCCION_GetOPxNUMERO_Result> CSP_METRICS_ORDENDESPRODUCCION_GetOPxNUMERO(string pNROOP)
        {
            var pNROOPParameter = pNROOP != null ?
                new ObjectParameter("PNROOP", pNROOP) :
                new ObjectParameter("PNROOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_METRICS_ORDENDESPRODUCCION_GetOPxNUMERO_Result>("CSP_METRICS_ORDENDESPRODUCCION_GetOPxNUMERO", pNROOPParameter);
        }
    
        public virtual ObjectResult<CSP_METRICS_ORDENDESPRODUCCION_GetProductListXOP_Result> CSP_METRICS_ORDENDESPRODUCCION_GetProductListXOP(string pNROOP)
        {
            var pNROOPParameter = pNROOP != null ?
                new ObjectParameter("PNROOP", pNROOP) :
                new ObjectParameter("PNROOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_METRICS_ORDENDESPRODUCCION_GetProductListXOP_Result>("CSP_METRICS_ORDENDESPRODUCCION_GetProductListXOP", pNROOPParameter);
        }
    
        public virtual ObjectResult<CSP_METRICS_SCRAP_ULT_7_DIAS_X_AREA_Result> CSP_METRICS_SCRAP_ULT_7_DIAS_X_AREA(Nullable<int> pIDAREA)
        {
            var pIDAREAParameter = pIDAREA.HasValue ?
                new ObjectParameter("PIDAREA", pIDAREA) :
                new ObjectParameter("PIDAREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_METRICS_SCRAP_ULT_7_DIAS_X_AREA_Result>("CSP_METRICS_SCRAP_ULT_7_DIAS_X_AREA", pIDAREAParameter);
        }
    
        public virtual ObjectResult<CSP_METRICS_TRAE_ACTIVIDADES_ORDEN_Result> CSP_METRICS_TRAE_ACTIVIDADES_ORDEN(string pNUMORDEM, string pNOMJOBTRACK, Nullable<int> pIDMAQUINA)
        {
            var pNUMORDEMParameter = pNUMORDEM != null ?
                new ObjectParameter("PNUMORDEM", pNUMORDEM) :
                new ObjectParameter("PNUMORDEM", typeof(string));
    
            var pNOMJOBTRACKParameter = pNOMJOBTRACK != null ?
                new ObjectParameter("PNOMJOBTRACK", pNOMJOBTRACK) :
                new ObjectParameter("PNOMJOBTRACK", typeof(string));
    
            var pIDMAQUINAParameter = pIDMAQUINA.HasValue ?
                new ObjectParameter("PIDMAQUINA", pIDMAQUINA) :
                new ObjectParameter("PIDMAQUINA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_METRICS_TRAE_ACTIVIDADES_ORDEN_Result>("CSP_METRICS_TRAE_ACTIVIDADES_ORDEN", pNUMORDEMParameter, pNOMJOBTRACKParameter, pIDMAQUINAParameter);
        }
    
        public virtual ObjectResult<CSP_METRIS_GET_PRODUCT_PARAMS_Result> CSP_METRIS_GET_PRODUCT_PARAMS(string pCodEstrutura)
        {
            var pCodEstruturaParameter = pCodEstrutura != null ?
                new ObjectParameter("pCodEstrutura", pCodEstrutura) :
                new ObjectParameter("pCodEstrutura", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_METRIS_GET_PRODUCT_PARAMS_Result>("CSP_METRIS_GET_PRODUCT_PARAMS", pCodEstruturaParameter);
        }
    
        public virtual ObjectResult<CSP_METRIS_GET_PRODUCT_PARAMS_X_OP_Result> CSP_METRIS_GET_PRODUCT_PARAMS_X_OP(string pNroOp)
        {
            var pNroOpParameter = pNroOp != null ?
                new ObjectParameter("pNroOp", pNroOp) :
                new ObjectParameter("pNroOp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_METRIS_GET_PRODUCT_PARAMS_X_OP_Result>("CSP_METRIS_GET_PRODUCT_PARAMS_X_OP", pNroOpParameter);
        }
    
        public virtual ObjectResult<CSP_METRIS_GET_PRODUCT_PARAMS_X_STRUCT_Result> CSP_METRIS_GET_PRODUCT_PARAMS_X_STRUCT(string pCodEstruct)
        {
            var pCodEstructParameter = pCodEstruct != null ?
                new ObjectParameter("pCodEstruct", pCodEstruct) :
                new ObjectParameter("pCodEstruct", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_METRIS_GET_PRODUCT_PARAMS_X_STRUCT_Result>("CSP_METRIS_GET_PRODUCT_PARAMS_X_STRUCT", pCodEstructParameter);
        }
    
        public virtual ObjectResult<CSP_PSSACTIVIDADES_TRAE_ACTIVIDAD_REPROCESO_Result> CSP_PSSACTIVIDADES_TRAE_ACTIVIDAD_REPROCESO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSACTIVIDADES_TRAE_ACTIVIDAD_REPROCESO_Result>("CSP_PSSACTIVIDADES_TRAE_ACTIVIDAD_REPROCESO");
        }
    
        public virtual ObjectResult<CSP_PSSACTIVIDADESMAQUINAS_CHECK_REPROCESO_ENABLED_Result> CSP_PSSACTIVIDADESMAQUINAS_CHECK_REPROCESO_ENABLED(Nullable<int> p_Id_Maquina)
        {
            var p_Id_MaquinaParameter = p_Id_Maquina.HasValue ?
                new ObjectParameter("P_Id_Maquina", p_Id_Maquina) :
                new ObjectParameter("P_Id_Maquina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSACTIVIDADESMAQUINAS_CHECK_REPROCESO_ENABLED_Result>("CSP_PSSACTIVIDADESMAQUINAS_CHECK_REPROCESO_ENABLED", p_Id_MaquinaParameter);
        }
    
        public virtual int CSP_PSSJOBTRACK_ACTIVE_PALLETS_CLEAN_JOBTRACK(string jOBTRACKNAME)
        {
            var jOBTRACKNAMEParameter = jOBTRACKNAME != null ?
                new ObjectParameter("JOBTRACKNAME", jOBTRACKNAME) :
                new ObjectParameter("JOBTRACKNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_PSSJOBTRACK_ACTIVE_PALLETS_CLEAN_JOBTRACK", jOBTRACKNAMEParameter);
        }
    
        public virtual int CSP_PSSJOBTRACK_ACTIVE_PALLETS_INSERT(string jOBTRACKNAME, string nUMOF, Nullable<int> nUMPALLET)
        {
            var jOBTRACKNAMEParameter = jOBTRACKNAME != null ?
                new ObjectParameter("JOBTRACKNAME", jOBTRACKNAME) :
                new ObjectParameter("JOBTRACKNAME", typeof(string));
    
            var nUMOFParameter = nUMOF != null ?
                new ObjectParameter("NUMOF", nUMOF) :
                new ObjectParameter("NUMOF", typeof(string));
    
            var nUMPALLETParameter = nUMPALLET.HasValue ?
                new ObjectParameter("NUMPALLET", nUMPALLET) :
                new ObjectParameter("NUMPALLET", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_PSSJOBTRACK_ACTIVE_PALLETS_INSERT", jOBTRACKNAMEParameter, nUMOFParameter, nUMPALLETParameter);
        }
    
        public virtual int CSP_PSSJOBTRACK_DISABLE_PALLETS(string jOBTRACKNAME, string nUMOF, Nullable<int> nUMPALLET)
        {
            var jOBTRACKNAMEParameter = jOBTRACKNAME != null ?
                new ObjectParameter("JOBTRACKNAME", jOBTRACKNAME) :
                new ObjectParameter("JOBTRACKNAME", typeof(string));
    
            var nUMOFParameter = nUMOF != null ?
                new ObjectParameter("NUMOF", nUMOF) :
                new ObjectParameter("NUMOF", typeof(string));
    
            var nUMPALLETParameter = nUMPALLET.HasValue ?
                new ObjectParameter("NUMPALLET", nUMPALLET) :
                new ObjectParameter("NUMPALLET", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_PSSJOBTRACK_DISABLE_PALLETS", jOBTRACKNAMEParameter, nUMOFParameter, nUMPALLETParameter);
        }
    
        public virtual ObjectResult<CSP_PSSJOBTRACKS_ACTIVE_PALLETS_OPENED_CHECK_OF_PALLET_Result> CSP_PSSJOBTRACKS_ACTIVE_PALLETS_OPENED_CHECK_OF_PALLET(string jOBTRACKNAME, Nullable<int> nUMOF, Nullable<int> nUMPALLET)
        {
            var jOBTRACKNAMEParameter = jOBTRACKNAME != null ?
                new ObjectParameter("JOBTRACKNAME", jOBTRACKNAME) :
                new ObjectParameter("JOBTRACKNAME", typeof(string));
    
            var nUMOFParameter = nUMOF.HasValue ?
                new ObjectParameter("NUMOF", nUMOF) :
                new ObjectParameter("NUMOF", typeof(int));
    
            var nUMPALLETParameter = nUMPALLET.HasValue ?
                new ObjectParameter("NUMPALLET", nUMPALLET) :
                new ObjectParameter("NUMPALLET", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSJOBTRACKS_ACTIVE_PALLETS_OPENED_CHECK_OF_PALLET_Result>("CSP_PSSJOBTRACKS_ACTIVE_PALLETS_OPENED_CHECK_OF_PALLET", jOBTRACKNAMEParameter, nUMOFParameter, nUMPALLETParameter);
        }
    
        public virtual ObjectResult<CSP_PSSJOBTRACKS_GET_PRINTERS_Result> CSP_PSSJOBTRACKS_GET_PRINTERS(string pJobtrackDNSName)
        {
            var pJobtrackDNSNameParameter = pJobtrackDNSName != null ?
                new ObjectParameter("pJobtrackDNSName", pJobtrackDNSName) :
                new ObjectParameter("pJobtrackDNSName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSJOBTRACKS_GET_PRINTERS_Result>("CSP_PSSJOBTRACKS_GET_PRINTERS", pJobtrackDNSNameParameter);
        }
    
        public virtual ObjectResult<CSP_PSSMAQUINAS_LISTAR_X_JOBTRACK_X_OPERADOR_Result> CSP_PSSMAQUINAS_LISTAR_X_JOBTRACK_X_OPERADOR(string pNOMJOBTRACK, Nullable<int> pOPERADOR)
        {
            var pNOMJOBTRACKParameter = pNOMJOBTRACK != null ?
                new ObjectParameter("PNOMJOBTRACK", pNOMJOBTRACK) :
                new ObjectParameter("PNOMJOBTRACK", typeof(string));
    
            var pOPERADORParameter = pOPERADOR.HasValue ?
                new ObjectParameter("POPERADOR", pOPERADOR) :
                new ObjectParameter("POPERADOR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSMAQUINAS_LISTAR_X_JOBTRACK_X_OPERADOR_Result>("CSP_PSSMAQUINAS_LISTAR_X_JOBTRACK_X_OPERADOR", pNOMJOBTRACKParameter, pOPERADORParameter);
        }
    
        public virtual ObjectResult<CSP_PSSOPERADORES_GET_DETALLE_Result> CSP_PSSOPERADORES_GET_DETALLE(Nullable<int> pIDOPERADOR)
        {
            var pIDOPERADORParameter = pIDOPERADOR.HasValue ?
                new ObjectParameter("PIDOPERADOR", pIDOPERADOR) :
                new ObjectParameter("PIDOPERADOR", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSOPERADORES_GET_DETALLE_Result>("CSP_PSSOPERADORES_GET_DETALLE", pIDOPERADORParameter);
        }
    
        public virtual ObjectResult<CSP_PSSOPERADORES_GET_DETALLE_X_LEGAJO_Result> CSP_PSSOPERADORES_GET_DETALLE_X_LEGAJO(Nullable<int> pLEGAJO)
        {
            var pLEGAJOParameter = pLEGAJO.HasValue ?
                new ObjectParameter("PLEGAJO", pLEGAJO) :
                new ObjectParameter("PLEGAJO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSOPERADORES_GET_DETALLE_X_LEGAJO_Result>("CSP_PSSOPERADORES_GET_DETALLE_X_LEGAJO", pLEGAJOParameter);
        }
    
        public virtual ObjectResult<CSP_PSSOPERADORES_GETALL_Result> CSP_PSSOPERADORES_GETALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSOPERADORES_GETALL_Result>("CSP_PSSOPERADORES_GETALL");
        }
    
        public virtual ObjectResult<CSP_PSSOPERARIOS_HABILITADOS_EMPAQUE_X_MAQUINA_Result> CSP_PSSOPERARIOS_HABILITADOS_EMPAQUE_X_MAQUINA(string pJOBTRACK, string pLEGAJO)
        {
            var pJOBTRACKParameter = pJOBTRACK != null ?
                new ObjectParameter("PJOBTRACK", pJOBTRACK) :
                new ObjectParameter("PJOBTRACK", typeof(string));
    
            var pLEGAJOParameter = pLEGAJO != null ?
                new ObjectParameter("pLEGAJO", pLEGAJO) :
                new ObjectParameter("pLEGAJO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSOPERARIOS_HABILITADOS_EMPAQUE_X_MAQUINA_Result>("CSP_PSSOPERARIOS_HABILITADOS_EMPAQUE_X_MAQUINA", pJOBTRACKParameter, pLEGAJOParameter);
        }
    
        public virtual int CSP_PSSORDENDESPRODUCCION_GETALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_PSSORDENDESPRODUCCION_GETALL");
        }
    
        public virtual int CSP_PSSORDENDESPRODUCCION_GetOPxNUMERO(Nullable<int> pNROOP)
        {
            var pNROOPParameter = pNROOP.HasValue ?
                new ObjectParameter("PNROOP", pNROOP) :
                new ObjectParameter("PNROOP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_PSSORDENDESPRODUCCION_GetOPxNUMERO", pNROOPParameter);
        }
    
        public virtual ObjectResult<CSP_PSSORIGENSCRAP_REPROCESO_Result> CSP_PSSORIGENSCRAP_REPROCESO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSORIGENSCRAP_REPROCESO_Result>("CSP_PSSORIGENSCRAP_REPROCESO");
        }
    
        public virtual ObjectResult<Nullable<decimal>> CSP_PSSROMANEO_INSERT(Nullable<int> pNroOF, string pCodProducto, string pDescProducto, Nullable<int> pNroPallet, string pTipoRomaneo, Nullable<int> pLegajo, Nullable<System.DateTime> pFecha, Nullable<int> pTurno, string pObs, Nullable<double> pPesoBruto, Nullable<double> pPesoNeto, string pCodCliente, string pNomCliente, Nullable<double> pTaraBuje, Nullable<double> pDistTacos, Nullable<double> pAncho)
        {
            var pNroOFParameter = pNroOF.HasValue ?
                new ObjectParameter("pNroOF", pNroOF) :
                new ObjectParameter("pNroOF", typeof(int));
    
            var pCodProductoParameter = pCodProducto != null ?
                new ObjectParameter("pCodProducto", pCodProducto) :
                new ObjectParameter("pCodProducto", typeof(string));
    
            var pDescProductoParameter = pDescProducto != null ?
                new ObjectParameter("pDescProducto", pDescProducto) :
                new ObjectParameter("pDescProducto", typeof(string));
    
            var pNroPalletParameter = pNroPallet.HasValue ?
                new ObjectParameter("pNroPallet", pNroPallet) :
                new ObjectParameter("pNroPallet", typeof(int));
    
            var pTipoRomaneoParameter = pTipoRomaneo != null ?
                new ObjectParameter("pTipoRomaneo", pTipoRomaneo) :
                new ObjectParameter("pTipoRomaneo", typeof(string));
    
            var pLegajoParameter = pLegajo.HasValue ?
                new ObjectParameter("pLegajo", pLegajo) :
                new ObjectParameter("pLegajo", typeof(int));
    
            var pFechaParameter = pFecha.HasValue ?
                new ObjectParameter("pFecha", pFecha) :
                new ObjectParameter("pFecha", typeof(System.DateTime));
    
            var pTurnoParameter = pTurno.HasValue ?
                new ObjectParameter("pTurno", pTurno) :
                new ObjectParameter("pTurno", typeof(int));
    
            var pObsParameter = pObs != null ?
                new ObjectParameter("pObs", pObs) :
                new ObjectParameter("pObs", typeof(string));
    
            var pPesoBrutoParameter = pPesoBruto.HasValue ?
                new ObjectParameter("pPesoBruto", pPesoBruto) :
                new ObjectParameter("pPesoBruto", typeof(double));
    
            var pPesoNetoParameter = pPesoNeto.HasValue ?
                new ObjectParameter("pPesoNeto", pPesoNeto) :
                new ObjectParameter("pPesoNeto", typeof(double));
    
            var pCodClienteParameter = pCodCliente != null ?
                new ObjectParameter("pCodCliente", pCodCliente) :
                new ObjectParameter("pCodCliente", typeof(string));
    
            var pNomClienteParameter = pNomCliente != null ?
                new ObjectParameter("pNomCliente", pNomCliente) :
                new ObjectParameter("pNomCliente", typeof(string));
    
            var pTaraBujeParameter = pTaraBuje.HasValue ?
                new ObjectParameter("pTaraBuje", pTaraBuje) :
                new ObjectParameter("pTaraBuje", typeof(double));
    
            var pDistTacosParameter = pDistTacos.HasValue ?
                new ObjectParameter("pDistTacos", pDistTacos) :
                new ObjectParameter("pDistTacos", typeof(double));
    
            var pAnchoParameter = pAncho.HasValue ?
                new ObjectParameter("pAncho", pAncho) :
                new ObjectParameter("pAncho", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CSP_PSSROMANEO_INSERT", pNroOFParameter, pCodProductoParameter, pDescProductoParameter, pNroPalletParameter, pTipoRomaneoParameter, pLegajoParameter, pFechaParameter, pTurnoParameter, pObsParameter, pPesoBrutoParameter, pPesoNetoParameter, pCodClienteParameter, pNomClienteParameter, pTaraBujeParameter, pDistTacosParameter, pAnchoParameter);
        }
    
        public virtual ObjectResult<CSP_PSSROMANEO_PRINT_CARTEL_Result> CSP_PSSROMANEO_PRINT_CARTEL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSROMANEO_PRINT_CARTEL_Result>("CSP_PSSROMANEO_PRINT_CARTEL");
        }
    
        public virtual ObjectResult<CSP_PSSROMANEO_PRINT_CARTEL_ALIMENTO_Result> CSP_PSSROMANEO_PRINT_CARTEL_ALIMENTO(Nullable<bool> alimento)
        {
            var alimentoParameter = alimento.HasValue ?
                new ObjectParameter("Alimento", alimento) :
                new ObjectParameter("Alimento", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSROMANEO_PRINT_CARTEL_ALIMENTO_Result>("CSP_PSSROMANEO_PRINT_CARTEL_ALIMENTO", alimentoParameter);
        }
    
        public virtual ObjectResult<CSP_PSSROMANEO_PRINT_COLDSEAL_Result> CSP_PSSROMANEO_PRINT_COLDSEAL(string pProducto)
        {
            var pProductoParameter = pProducto != null ?
                new ObjectParameter("PProducto", pProducto) :
                new ObjectParameter("PProducto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSROMANEO_PRINT_COLDSEAL_Result>("CSP_PSSROMANEO_PRINT_COLDSEAL", pProductoParameter);
        }
    
        public virtual int CSP_PSSROMANEOITEMS_INSERT(Nullable<int> pIdRomaneo, Nullable<int> pNroBulto, Nullable<int> pBobinas, Nullable<double> pUnidades, Nullable<double> pMts, Nullable<double> pPesoBruto, Nullable<double> pPesoNeto, Nullable<int> pEtiquetasBobina, Nullable<double> pMts2)
        {
            var pIdRomaneoParameter = pIdRomaneo.HasValue ?
                new ObjectParameter("pIdRomaneo", pIdRomaneo) :
                new ObjectParameter("pIdRomaneo", typeof(int));
    
            var pNroBultoParameter = pNroBulto.HasValue ?
                new ObjectParameter("pNroBulto", pNroBulto) :
                new ObjectParameter("pNroBulto", typeof(int));
    
            var pBobinasParameter = pBobinas.HasValue ?
                new ObjectParameter("pBobinas", pBobinas) :
                new ObjectParameter("pBobinas", typeof(int));
    
            var pUnidadesParameter = pUnidades.HasValue ?
                new ObjectParameter("pUnidades", pUnidades) :
                new ObjectParameter("pUnidades", typeof(double));
    
            var pMtsParameter = pMts.HasValue ?
                new ObjectParameter("pMts", pMts) :
                new ObjectParameter("pMts", typeof(double));
    
            var pPesoBrutoParameter = pPesoBruto.HasValue ?
                new ObjectParameter("pPesoBruto", pPesoBruto) :
                new ObjectParameter("pPesoBruto", typeof(double));
    
            var pPesoNetoParameter = pPesoNeto.HasValue ?
                new ObjectParameter("pPesoNeto", pPesoNeto) :
                new ObjectParameter("pPesoNeto", typeof(double));
    
            var pEtiquetasBobinaParameter = pEtiquetasBobina.HasValue ?
                new ObjectParameter("pEtiquetasBobina", pEtiquetasBobina) :
                new ObjectParameter("pEtiquetasBobina", typeof(int));
    
            var pMts2Parameter = pMts2.HasValue ?
                new ObjectParameter("pMts2", pMts2) :
                new ObjectParameter("pMts2", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_PSSROMANEOITEMS_INSERT", pIdRomaneoParameter, pNroBultoParameter, pBobinasParameter, pUnidadesParameter, pMtsParameter, pPesoBrutoParameter, pPesoNetoParameter, pEtiquetasBobinaParameter, pMts2Parameter);
        }
    
        public virtual ObjectResult<CSP_PSSRROMANEO_DELETE_X_OF_X_PALLET_Result> CSP_PSSRROMANEO_DELETE_X_OF_X_PALLET(Nullable<int> pNroOF, Nullable<int> pNroPallet)
        {
            var pNroOFParameter = pNroOF.HasValue ?
                new ObjectParameter("pNroOF", pNroOF) :
                new ObjectParameter("pNroOF", typeof(int));
    
            var pNroPalletParameter = pNroPallet.HasValue ?
                new ObjectParameter("pNroPallet", pNroPallet) :
                new ObjectParameter("pNroPallet", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSRROMANEO_DELETE_X_OF_X_PALLET_Result>("CSP_PSSRROMANEO_DELETE_X_OF_X_PALLET", pNroOFParameter, pNroPalletParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CSP_PSSRROMANEO_GET_LAST_OF_PRINTED(string pTipoRomaneo)
        {
            var pTipoRomaneoParameter = pTipoRomaneo != null ?
                new ObjectParameter("pTipoRomaneo", pTipoRomaneo) :
                new ObjectParameter("pTipoRomaneo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CSP_PSSRROMANEO_GET_LAST_OF_PRINTED", pTipoRomaneoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CSP_PSSRROMANEO_GET_NEXT_PALLET_NUMBER(Nullable<int> pNroOf)
        {
            var pNroOfParameter = pNroOf.HasValue ?
                new ObjectParameter("pNroOf", pNroOf) :
                new ObjectParameter("pNroOf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CSP_PSSRROMANEO_GET_NEXT_PALLET_NUMBER", pNroOfParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CSP_PSSRROMANEO_GET_NEXT_PALLET_NUMBER_BK_20221028(Nullable<int> pNroOf)
        {
            var pNroOfParameter = pNroOf.HasValue ?
                new ObjectParameter("pNroOf", pNroOf) :
                new ObjectParameter("pNroOf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CSP_PSSRROMANEO_GET_NEXT_PALLET_NUMBER_BK_20221028", pNroOfParameter);
        }
    
        public virtual int CSP_PSSSCRAP_DELETE(Nullable<int> pREGID)
        {
            var pREGIDParameter = pREGID.HasValue ?
                new ObjectParameter("PREGID", pREGID) :
                new ObjectParameter("PREGID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_PSSSCRAP_DELETE", pREGIDParameter);
        }
    
        public virtual ObjectResult<CSP_PSSSCRAP_LISTAR_X_JOBTRACK_Result> CSP_PSSSCRAP_LISTAR_X_JOBTRACK(string pJOBTRACKNAME)
        {
            var pJOBTRACKNAMEParameter = pJOBTRACKNAME != null ?
                new ObjectParameter("PJOBTRACKNAME", pJOBTRACKNAME) :
                new ObjectParameter("PJOBTRACKNAME", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_PSSSCRAP_LISTAR_X_JOBTRACK_Result>("CSP_PSSSCRAP_LISTAR_X_JOBTRACK", pJOBTRACKNAMEParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CSP_PSSTABACOBOBINAS_GET_PROX_BOBINA_X_OF(Nullable<int> pNROOF)
        {
            var pNROOFParameter = pNROOF.HasValue ?
                new ObjectParameter("PNROOF", pNROOF) :
                new ObjectParameter("PNROOF", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CSP_PSSTABACOBOBINAS_GET_PROX_BOBINA_X_OF", pNROOFParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CSP_PSSTABACOBOBINAS_GET_PROX_PALLET_X_OF(Nullable<int> pNROOF)
        {
            var pNROOFParameter = pNROOF.HasValue ?
                new ObjectParameter("PNROOF", pNROOF) :
                new ObjectParameter("PNROOF", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CSP_PSSTABACOBOBINAS_GET_PROX_PALLET_X_OF", pNROOFParameter);
        }
    
        public virtual int CSP_PSSTABACOBOBINAS_INSERT(Nullable<int> nROOF, string cODPRODUCTO, string dESCPRODUCTO, string cODITEMPMI, Nullable<int> lEGAJO, Nullable<System.DateTime> fECHAPROD, Nullable<System.DateTime> fECHAREG, Nullable<System.DateTime> fECHAVTO, Nullable<double> lARGO, Nullable<int> nROBOBINA, string oBS)
        {
            var nROOFParameter = nROOF.HasValue ?
                new ObjectParameter("NROOF", nROOF) :
                new ObjectParameter("NROOF", typeof(int));
    
            var cODPRODUCTOParameter = cODPRODUCTO != null ?
                new ObjectParameter("CODPRODUCTO", cODPRODUCTO) :
                new ObjectParameter("CODPRODUCTO", typeof(string));
    
            var dESCPRODUCTOParameter = dESCPRODUCTO != null ?
                new ObjectParameter("DESCPRODUCTO", dESCPRODUCTO) :
                new ObjectParameter("DESCPRODUCTO", typeof(string));
    
            var cODITEMPMIParameter = cODITEMPMI != null ?
                new ObjectParameter("CODITEMPMI", cODITEMPMI) :
                new ObjectParameter("CODITEMPMI", typeof(string));
    
            var lEGAJOParameter = lEGAJO.HasValue ?
                new ObjectParameter("LEGAJO", lEGAJO) :
                new ObjectParameter("LEGAJO", typeof(int));
    
            var fECHAPRODParameter = fECHAPROD.HasValue ?
                new ObjectParameter("FECHAPROD", fECHAPROD) :
                new ObjectParameter("FECHAPROD", typeof(System.DateTime));
    
            var fECHAREGParameter = fECHAREG.HasValue ?
                new ObjectParameter("FECHAREG", fECHAREG) :
                new ObjectParameter("FECHAREG", typeof(System.DateTime));
    
            var fECHAVTOParameter = fECHAVTO.HasValue ?
                new ObjectParameter("FECHAVTO", fECHAVTO) :
                new ObjectParameter("FECHAVTO", typeof(System.DateTime));
    
            var lARGOParameter = lARGO.HasValue ?
                new ObjectParameter("LARGO", lARGO) :
                new ObjectParameter("LARGO", typeof(double));
    
            var nROBOBINAParameter = nROBOBINA.HasValue ?
                new ObjectParameter("NROBOBINA", nROBOBINA) :
                new ObjectParameter("NROBOBINA", typeof(int));
    
            var oBSParameter = oBS != null ?
                new ObjectParameter("OBS", oBS) :
                new ObjectParameter("OBS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_PSSTABACOBOBINAS_INSERT", nROOFParameter, cODPRODUCTOParameter, dESCPRODUCTOParameter, cODITEMPMIParameter, lEGAJOParameter, fECHAPRODParameter, fECHAREGParameter, fECHAVTOParameter, lARGOParameter, nROBOBINAParameter, oBSParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CSP_PSSTABACOPALLETS_GET_LASTTOTALPALLETNUMBER(Nullable<int> nROOF)
        {
            var nROOFParameter = nROOF.HasValue ?
                new ObjectParameter("NROOF", nROOF) :
                new ObjectParameter("NROOF", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CSP_PSSTABACOPALLETS_GET_LASTTOTALPALLETNUMBER", nROOFParameter);
        }
    
        public virtual int CSP_PSSTABACOPALLETS_INSERT(Nullable<int> nROOF, string cODPRODUCTO, string dESCPRODUCTO, string nROORDENPMI, string nROIDENTIFICADOR, string cODITEMPMI, Nullable<int> lEGAJO, Nullable<System.DateTime> fECHAPROD, Nullable<System.DateTime> fECHAREG, Nullable<System.DateTime> fECHAVTO, Nullable<int> nRO_PALLET, Nullable<int> tOTAL_PALLETS, Nullable<int> cANT_BOBINAS, Nullable<decimal> pESO_BRUTO, Nullable<decimal> pESO_NETO, string oBS)
        {
            var nROOFParameter = nROOF.HasValue ?
                new ObjectParameter("NROOF", nROOF) :
                new ObjectParameter("NROOF", typeof(int));
    
            var cODPRODUCTOParameter = cODPRODUCTO != null ?
                new ObjectParameter("CODPRODUCTO", cODPRODUCTO) :
                new ObjectParameter("CODPRODUCTO", typeof(string));
    
            var dESCPRODUCTOParameter = dESCPRODUCTO != null ?
                new ObjectParameter("DESCPRODUCTO", dESCPRODUCTO) :
                new ObjectParameter("DESCPRODUCTO", typeof(string));
    
            var nROORDENPMIParameter = nROORDENPMI != null ?
                new ObjectParameter("NROORDENPMI", nROORDENPMI) :
                new ObjectParameter("NROORDENPMI", typeof(string));
    
            var nROIDENTIFICADORParameter = nROIDENTIFICADOR != null ?
                new ObjectParameter("NROIDENTIFICADOR", nROIDENTIFICADOR) :
                new ObjectParameter("NROIDENTIFICADOR", typeof(string));
    
            var cODITEMPMIParameter = cODITEMPMI != null ?
                new ObjectParameter("CODITEMPMI", cODITEMPMI) :
                new ObjectParameter("CODITEMPMI", typeof(string));
    
            var lEGAJOParameter = lEGAJO.HasValue ?
                new ObjectParameter("LEGAJO", lEGAJO) :
                new ObjectParameter("LEGAJO", typeof(int));
    
            var fECHAPRODParameter = fECHAPROD.HasValue ?
                new ObjectParameter("FECHAPROD", fECHAPROD) :
                new ObjectParameter("FECHAPROD", typeof(System.DateTime));
    
            var fECHAREGParameter = fECHAREG.HasValue ?
                new ObjectParameter("FECHAREG", fECHAREG) :
                new ObjectParameter("FECHAREG", typeof(System.DateTime));
    
            var fECHAVTOParameter = fECHAVTO.HasValue ?
                new ObjectParameter("FECHAVTO", fECHAVTO) :
                new ObjectParameter("FECHAVTO", typeof(System.DateTime));
    
            var nRO_PALLETParameter = nRO_PALLET.HasValue ?
                new ObjectParameter("NRO_PALLET", nRO_PALLET) :
                new ObjectParameter("NRO_PALLET", typeof(int));
    
            var tOTAL_PALLETSParameter = tOTAL_PALLETS.HasValue ?
                new ObjectParameter("TOTAL_PALLETS", tOTAL_PALLETS) :
                new ObjectParameter("TOTAL_PALLETS", typeof(int));
    
            var cANT_BOBINASParameter = cANT_BOBINAS.HasValue ?
                new ObjectParameter("CANT_BOBINAS", cANT_BOBINAS) :
                new ObjectParameter("CANT_BOBINAS", typeof(int));
    
            var pESO_BRUTOParameter = pESO_BRUTO.HasValue ?
                new ObjectParameter("PESO_BRUTO", pESO_BRUTO) :
                new ObjectParameter("PESO_BRUTO", typeof(decimal));
    
            var pESO_NETOParameter = pESO_NETO.HasValue ?
                new ObjectParameter("PESO_NETO", pESO_NETO) :
                new ObjectParameter("PESO_NETO", typeof(decimal));
    
            var oBSParameter = oBS != null ?
                new ObjectParameter("OBS", oBS) :
                new ObjectParameter("OBS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_PSSTABACOPALLETS_INSERT", nROOFParameter, cODPRODUCTOParameter, dESCPRODUCTOParameter, nROORDENPMIParameter, nROIDENTIFICADORParameter, cODITEMPMIParameter, lEGAJOParameter, fECHAPRODParameter, fECHAREGParameter, fECHAVTOParameter, nRO_PALLETParameter, tOTAL_PALLETSParameter, cANT_BOBINASParameter, pESO_BRUTOParameter, pESO_NETOParameter, oBSParameter);
        }
    
        public virtual ObjectResult<CSP_REPORTE_EFICIENCIA_X_FECHAS_NUMOREDEN_CERRADAS_Result> CSP_REPORTE_EFICIENCIA_X_FECHAS_NUMOREDEN_CERRADAS(Nullable<System.DateTime> pFECHADESDE, Nullable<System.DateTime> pFECHAHASTA, string pESTADOOP)
        {
            var pFECHADESDEParameter = pFECHADESDE.HasValue ?
                new ObjectParameter("PFECHADESDE", pFECHADESDE) :
                new ObjectParameter("PFECHADESDE", typeof(System.DateTime));
    
            var pFECHAHASTAParameter = pFECHAHASTA.HasValue ?
                new ObjectParameter("PFECHAHASTA", pFECHAHASTA) :
                new ObjectParameter("PFECHAHASTA", typeof(System.DateTime));
    
            var pESTADOOPParameter = pESTADOOP != null ?
                new ObjectParameter("PESTADOOP", pESTADOOP) :
                new ObjectParameter("PESTADOOP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_REPORTE_EFICIENCIA_X_FECHAS_NUMOREDEN_CERRADAS_Result>("CSP_REPORTE_EFICIENCIA_X_FECHAS_NUMOREDEN_CERRADAS", pFECHADESDEParameter, pFECHAHASTAParameter, pESTADOOPParameter);
        }
    
        public virtual ObjectResult<CSP_REPORTE_EFICIENCIA_X_NUMORDEN_CERRADA_Result> CSP_REPORTE_EFICIENCIA_X_NUMORDEN_CERRADA(Nullable<int> nUMOP)
        {
            var nUMOPParameter = nUMOP.HasValue ?
                new ObjectParameter("NUMOP", nUMOP) :
                new ObjectParameter("NUMOP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_REPORTE_EFICIENCIA_X_NUMORDEN_CERRADA_Result>("CSP_REPORTE_EFICIENCIA_X_NUMORDEN_CERRADA", nUMOPParameter);
        }
    
        public virtual ObjectResult<CSP_REPORTE_ROMANEO_Result> CSP_REPORTE_ROMANEO(Nullable<int> pNroOf, string pCodProducto, Nullable<System.DateTime> pFechaDesde, Nullable<System.DateTime> pFechaHasta, Nullable<int> pTurno, string pTipoRomaneo)
        {
            var pNroOfParameter = pNroOf.HasValue ?
                new ObjectParameter("PNroOf", pNroOf) :
                new ObjectParameter("PNroOf", typeof(int));
    
            var pCodProductoParameter = pCodProducto != null ?
                new ObjectParameter("PCodProducto", pCodProducto) :
                new ObjectParameter("PCodProducto", typeof(string));
    
            var pFechaDesdeParameter = pFechaDesde.HasValue ?
                new ObjectParameter("PFechaDesde", pFechaDesde) :
                new ObjectParameter("PFechaDesde", typeof(System.DateTime));
    
            var pFechaHastaParameter = pFechaHasta.HasValue ?
                new ObjectParameter("PFechaHasta", pFechaHasta) :
                new ObjectParameter("PFechaHasta", typeof(System.DateTime));
    
            var pTurnoParameter = pTurno.HasValue ?
                new ObjectParameter("PTurno", pTurno) :
                new ObjectParameter("PTurno", typeof(int));
    
            var pTipoRomaneoParameter = pTipoRomaneo != null ?
                new ObjectParameter("PTipoRomaneo", pTipoRomaneo) :
                new ObjectParameter("PTipoRomaneo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_REPORTE_ROMANEO_Result>("CSP_REPORTE_ROMANEO", pNroOfParameter, pCodProductoParameter, pFechaDesdeParameter, pFechaHastaParameter, pTurnoParameter, pTipoRomaneoParameter);
        }
    
        public virtual ObjectResult<CSP_REPORTE_SCRAP_Result> CSP_REPORTE_SCRAP(Nullable<System.DateTime> fECHA_INI, Nullable<System.DateTime> fECHA_FIN)
        {
            var fECHA_INIParameter = fECHA_INI.HasValue ?
                new ObjectParameter("FECHA_INI", fECHA_INI) :
                new ObjectParameter("FECHA_INI", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_REPORTE_SCRAP_Result>("CSP_REPORTE_SCRAP", fECHA_INIParameter, fECHA_FINParameter);
        }
    
        public virtual ObjectResult<CSP_RPT_SCRAP_IMPRESORA_Result> CSP_RPT_SCRAP_IMPRESORA(Nullable<int> pIDREGSCRAP)
        {
            var pIDREGSCRAPParameter = pIDREGSCRAP.HasValue ?
                new ObjectParameter("PIDREGSCRAP", pIDREGSCRAP) :
                new ObjectParameter("PIDREGSCRAP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_RPT_SCRAP_IMPRESORA_Result>("CSP_RPT_SCRAP_IMPRESORA", pIDREGSCRAPParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> CSP_SCRAP_INSERT(Nullable<System.DateTime> pFECHA, Nullable<int> pNUMOP, Nullable<int> pIDMAQ, Nullable<int> pIDOPERADOR, Nullable<int> pIDACTIVIDAD, Nullable<int> pIDTIPOMAQ, Nullable<int> pIDORISCRAP, Nullable<decimal> pPESO, string pOBS, Nullable<bool> pHABILITADO)
        {
            var pFECHAParameter = pFECHA.HasValue ?
                new ObjectParameter("PFECHA", pFECHA) :
                new ObjectParameter("PFECHA", typeof(System.DateTime));
    
            var pNUMOPParameter = pNUMOP.HasValue ?
                new ObjectParameter("PNUMOP", pNUMOP) :
                new ObjectParameter("PNUMOP", typeof(int));
    
            var pIDMAQParameter = pIDMAQ.HasValue ?
                new ObjectParameter("PIDMAQ", pIDMAQ) :
                new ObjectParameter("PIDMAQ", typeof(int));
    
            var pIDOPERADORParameter = pIDOPERADOR.HasValue ?
                new ObjectParameter("PIDOPERADOR", pIDOPERADOR) :
                new ObjectParameter("PIDOPERADOR", typeof(int));
    
            var pIDACTIVIDADParameter = pIDACTIVIDAD.HasValue ?
                new ObjectParameter("PIDACTIVIDAD", pIDACTIVIDAD) :
                new ObjectParameter("PIDACTIVIDAD", typeof(int));
    
            var pIDTIPOMAQParameter = pIDTIPOMAQ.HasValue ?
                new ObjectParameter("PIDTIPOMAQ", pIDTIPOMAQ) :
                new ObjectParameter("PIDTIPOMAQ", typeof(int));
    
            var pIDORISCRAPParameter = pIDORISCRAP.HasValue ?
                new ObjectParameter("PIDORISCRAP", pIDORISCRAP) :
                new ObjectParameter("PIDORISCRAP", typeof(int));
    
            var pPESOParameter = pPESO.HasValue ?
                new ObjectParameter("PPESO", pPESO) :
                new ObjectParameter("PPESO", typeof(decimal));
    
            var pOBSParameter = pOBS != null ?
                new ObjectParameter("POBS", pOBS) :
                new ObjectParameter("POBS", typeof(string));
    
            var pHABILITADOParameter = pHABILITADO.HasValue ?
                new ObjectParameter("PHABILITADO", pHABILITADO) :
                new ObjectParameter("PHABILITADO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("CSP_SCRAP_INSERT", pFECHAParameter, pNUMOPParameter, pIDMAQParameter, pIDOPERADORParameter, pIDACTIVIDADParameter, pIDTIPOMAQParameter, pIDORISCRAPParameter, pPESOParameter, pOBSParameter, pHABILITADOParameter);
        }
    
        public virtual int CSP_SCRAP_MOTIVOS_TABLE_TOTAL_AÑO_ANT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_SCRAP_MOTIVOS_TABLE_TOTAL_AÑO_ANT");
        }
    
        public virtual ObjectResult<CSP_SCRAP_MOTIVOS_TABLE1_Result> CSP_SCRAP_MOTIVOS_TABLE1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_SCRAP_MOTIVOS_TABLE1_Result>("CSP_SCRAP_MOTIVOS_TABLE1");
        }
    
        public virtual ObjectResult<CSP_SCRAP_MOTIVOS_TABLE2_Result> CSP_SCRAP_MOTIVOS_TABLE2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_SCRAP_MOTIVOS_TABLE2_Result>("CSP_SCRAP_MOTIVOS_TABLE2");
        }
    
        public virtual ObjectResult<CSP_TABACO_GET_LAST_PRINT_DATE_BY_OP_Result> CSP_TABACO_GET_LAST_PRINT_DATE_BY_OP(Nullable<int> pNroOf)
        {
            var pNroOfParameter = pNroOf.HasValue ?
                new ObjectParameter("pNroOf", pNroOf) :
                new ObjectParameter("pNroOf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CSP_TABACO_GET_LAST_PRINT_DATE_BY_OP_Result>("CSP_TABACO_GET_LAST_PRINT_DATE_BY_OP", pNroOfParameter);
        }
    
        public virtual int CSP_TABACO_GET_VISUAL_OC_INFO(string pO_REF, string pART_ID)
        {
            var pO_REFParameter = pO_REF != null ?
                new ObjectParameter("PO_REF", pO_REF) :
                new ObjectParameter("PO_REF", typeof(string));
    
            var pART_IDParameter = pART_ID != null ?
                new ObjectParameter("PART_ID", pART_ID) :
                new ObjectParameter("PART_ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CSP_TABACO_GET_VISUAL_OC_INFO", pO_REFParameter, pART_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> CSP_TRAZABILIDAD_GET_PROX_DESDE(Nullable<int> nROOF, Nullable<int> tIPO)
        {
            var nROOFParameter = nROOF.HasValue ?
                new ObjectParameter("NROOF", nROOF) :
                new ObjectParameter("NROOF", typeof(int));
    
            var tIPOParameter = tIPO.HasValue ?
                new ObjectParameter("TIPO", tIPO) :
                new ObjectParameter("TIPO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("CSP_TRAZABILIDAD_GET_PROX_DESDE", nROOFParameter, tIPOParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_154f00f8_e3d5_49d2_8cf2_12cd5bad5863()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_154f00f8_e3d5_49d2_8cf2_12cd5bad5863");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_16d32cc3_e8b0_4f29_b65b_8e437f94188f()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_16d32cc3_e8b0_4f29_b65b_8e437f94188f");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_39a7623c_1082_459d_a4bf_3bc992a73d3e()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_39a7623c_1082_459d_a4bf_3bc992a73d3e");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_4a920ba5_d26e_4e4f_aa41_bb0b68bc457c()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_4a920ba5_d26e_4e4f_aa41_bb0b68bc457c");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_6ffbdbf3_8efc_4293_af11_e35bd166148e()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_6ffbdbf3_8efc_4293_af11_e35bd166148e");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_9d17e98e_f0a9_4763_9e34_b7126298eddc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_9d17e98e_f0a9_4763_9e34_b7126298eddc");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_9dadaad6_0463_4844_8bd0_05f4a392aced()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_9dadaad6_0463_4844_8bd0_05f4a392aced");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_a9dd2b45_93ba_42ec_957e_c56ec28aec45()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_a9dd2b45_93ba_42ec_957e_c56ec28aec45");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_cc217855_33d3_4350_b0ef_9686b11dae73()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_cc217855_33d3_4350_b0ef_9686b11dae73");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_de3b0173_8e28_4ecc_a4cd_de9318c4fd27()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_de3b0173_8e28_4ecc_a4cd_de9318c4fd27");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_e9ad8ab2_5a30_411e_8587_3613f9110a91()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_e9ad8ab2_5a30_411e_8587_3613f9110a91");
        }
    }
}
