//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSJobtrackModulos
    {
        public int IdJobtrack { get; set; }
        public int IdModuloApp { get; set; }
        public string Descripcion { get; set; }
    
        public virtual PSSJobTrack PSSJobTrack { get; set; }
    }
}
