//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSJobTrack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PSSJobTrack()
        {
            this.PSSJobtrackModulos = new HashSet<PSSJobtrackModulos>();
            this.PSSMaquinas = new HashSet<PSSMaquinas>();
        }
    
        public int IDJobTrack { get; set; }
        public string Descripcion { get; set; }
        public string JobTrack { get; set; }
        public bool Habilitado { get; set; }
        public string PrinterDefault { get; set; }
        public string PrinterEtiquetas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSJobtrackModulos> PSSJobtrackModulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSMaquinas> PSSMaquinas { get; set; }
    }
}
