//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSMotivosScrap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PSSMotivosScrap()
        {
            this.PSSMotivosScrapObjetivos = new HashSet<PSSMotivosScrapObjetivos>();
            this.PSSMotivosScrapVinculos = new HashSet<PSSMotivosScrapVinculos>();
        }
    
        public int Id_Motivo { get; set; }
        public string Descripcion { get; set; }
        public bool Habilitado { get; set; }
        public Nullable<double> PorcentajeSimulacionMejora { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSMotivosScrapObjetivos> PSSMotivosScrapObjetivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSMotivosScrapVinculos> PSSMotivosScrapVinculos { get; set; }
    }
}
