//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSMaquinas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PSSMaquinas()
        {
            this.PSSMotivosScrapVinculos = new HashSet<PSSMotivosScrapVinculos>();
            this.PSSScrap = new HashSet<PSSScrap>();
            this.PSSActividades = new HashSet<PSSActividades>();
            this.PSSJobTrack = new HashSet<PSSJobTrack>();
            this.PSSOperadores = new HashSet<PSSOperadores>();
            this.PSSOrigenesScrap = new HashSet<PSSOrigenesScrap>();
            this.PSSTiposMaterial = new HashSet<PSSTiposMaterial>();
        }
    
        public int IDMaq { get; set; }
        public string Descripcion { get; set; }
        public string Recurso { get; set; }
        public int IDArea { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual PSSAreas PSSAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSMotivosScrapVinculos> PSSMotivosScrapVinculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSScrap> PSSScrap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSActividades> PSSActividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSJobTrack> PSSJobTrack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSOperadores> PSSOperadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSOrigenesScrap> PSSOrigenesScrap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSTiposMaterial> PSSTiposMaterial { get; set; }
    }
}
