//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSMotivosScrapObjetivos
    {
        public int Id_Objetivo { get; set; }
        public int Id_Motivo { get; set; }
        public double Indicador_Inicio { get; set; }
        public double Indicador_Objetivo { get; set; }
        public System.DateTime Vigencia_Desde { get; set; }
        public System.DateTime Vigencia_Hasta { get; set; }
    
        public virtual PSSMotivosScrap PSSMotivosScrap { get; set; }
    }
}
