//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSMotivosScrapVinculos
    {
        public int Id_Motivo { get; set; }
        public int Id_Recurso { get; set; }
        public int Id_Origen { get; set; }
        public int Id_MaquinaImpute { get; set; }
        public int Id_TipoMaterial { get; set; }
    
        public virtual Metrics_Recursos_Habilitados Metrics_Recursos_Habilitados { get; set; }
        public virtual PSSMaquinas PSSMaquinas { get; set; }
        public virtual PSSMotivosScrap PSSMotivosScrap { get; set; }
        public virtual PSSOrigenesScrap PSSOrigenesScrap { get; set; }
        public virtual PSSTiposMaterial PSSTiposMaterial { get; set; }
    }
}
