//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSOrigenesScrap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PSSOrigenesScrap()
        {
            this.PSSMotivosScrapVinculos = new HashSet<PSSMotivosScrapVinculos>();
            this.PSSScrap = new HashSet<PSSScrap>();
            this.PSSMaquinas = new HashSet<PSSMaquinas>();
            this.PSSTiposMaterial = new HashSet<PSSTiposMaterial>();
        }
    
        public int IDOrigen { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdMaquina { get; set; }
        public bool Habilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSMotivosScrapVinculos> PSSMotivosScrapVinculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSScrap> PSSScrap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSMaquinas> PSSMaquinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSTiposMaterial> PSSTiposMaterial { get; set; }
    }
}
