//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSRomaneo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PSSRomaneo()
        {
            this.PSSRomaneoItems = new HashSet<PSSRomaneoItems>();
        }
    
        public int IdRomaneo { get; set; }
        public int NroOf { get; set; }
        public string CodProducto { get; set; }
        public string DescProducto { get; set; }
        public int NroPallet { get; set; }
        public string TipoRomaneo { get; set; }
        public int Legajo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Turno { get; set; }
        public string Obs { get; set; }
        public double PesoBruto { get; set; }
        public double PesoNeto { get; set; }
        public string CodCliente { get; set; }
        public string NomCliente { get; set; }
        public double TaraBuje { get; set; }
        public double DistTacos { get; set; }
        public double Ancho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PSSRomaneoItems> PSSRomaneoItems { get; set; }
    }
}
