//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSRomaneoItems
    {
        public int IdRomaneo { get; set; }
        public int NroBulto { get; set; }
        public int Unidades { get; set; }
        public int Bobinas { get; set; }
        public double Mts { get; set; }
        public double PesoBruto { get; set; }
        public double PesoNeto { get; set; }
        public int EtiquetasXBobina { get; set; }
        public double Mts2 { get; set; }
    
        public virtual PSSRomaneo PSSRomaneo { get; set; }
    }
}
