//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSScrapValoresPorPeriodoMensual
    {
        public int Ano { get; set; }
        public int Mes { get; set; }
        public double TonsProducidas { get; set; }
        public double ScrapNoRegistrado { get; set; }
        public int Record_Id { get; set; }
    }
}
