//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSScrap
    {
        public int IdRegScrap { get; set; }
        public System.DateTime Fecha { get; set; }
        public int NumOP { get; set; }
        public int IdMaq { get; set; }
        public int IdOperador { get; set; }
        public int IdActividad { get; set; }
        public int IdTipoMat { get; set; }
        public int IdOrigenScrap { get; set; }
        public decimal Peso { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int IdMaqImputaScrap { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual PSSActividades PSSActividades { get; set; }
        public virtual PSSMaquinas PSSMaquinas { get; set; }
        public virtual PSSOperadores PSSOperadores { get; set; }
        public virtual PSSOrigenesScrap PSSOrigenesScrap { get; set; }
        public virtual PSSTiposMaterial PSSTiposMaterial { get; set; }
    }
}
