//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSSTabacoPallets
    {
        public long RecordId { get; set; }
        public int NroOf { get; set; }
        public string CodProducto { get; set; }
        public string DescProducto { get; set; }
        public string NroOrdenPMI { get; set; }
        public string NroIdentificador { get; set; }
        public string CodItemPMI { get; set; }
        public int Legajo { get; set; }
        public System.DateTime FechaProd { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaVto { get; set; }
        public int NroPallet { get; set; }
        public int TotalPallets { get; set; }
        public decimal CantBobinas { get; set; }
        public decimal PesoBruto { get; set; }
        public decimal PesoNeto { get; set; }
        public string Obs { get; set; }
        public bool D_E_L_E_T_E_D { get; set; }
    }
}
