//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudTintas
    {
        public int IdSolicitud { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public int NroOf { get; set; }
        public string CodProducto { get; set; }
        public int Legajo { get; set; }
        public System.DateTime FechaRequerida { get; set; }
        public string Secat { get; set; }
        public string Tinta { get; set; }
        public string Viscosidad { get; set; }
        public double MtsImpresos { get; set; }
        public double MtsRestantes { get; set; }
        public string KgSolicitados { get; set; }
        public string Obs { get; set; }
        public int Estado { get; set; }
        public int IdMaquina { get; set; }
        public int IdJobtrack { get; set; }
    
        public virtual SolicitudTintasEstados SolicitudTintasEstados { get; set; }
    }
}
