//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudTintasTrazabilidad
    {
        public long RecordId { get; set; }
        public int IdSolicitud { get; set; }
        public int Estado { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Legajo { get; set; }
    }
}
