//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trazabilidad
    {
        public long IdTrazabilidad { get; set; }
        public int NroOP { get; set; }
        public string TipoTrazabilidad { get; set; }
        public int Legajo { get; set; }
        public int CantidadGenerada { get; set; }
        public int Desde { get; set; }
        public int Hasta { get; set; }
        public System.DateTime Fecha { get; set; }
        public int CantidadElementos { get; set; }
        public double Metros { get; set; }
        public bool Muestra { get; set; }
    }
}
