//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_USR_M3_ORDATIVIDADES_AC_test
    {
        public string NumOrdem { get; set; }
        public string NomeCliente { get; set; }
        public int idAtiv { get; set; }
        public string Idprocesso { get; set; }
        public string obs { get; set; }
        public string Titulo { get; set; }
        public double QtdPlanejada { get; set; }
        public double QtdProduzida { get; set; }
        public int QtdRepeticoes { get; set; }
        public int QtdEntradas { get; set; }
        public int GrupoAtivOP { get; set; }
        public double ProducaoHora { get; set; }
        public string CodAtiv { get; set; }
        public int PerdaFixa { get; set; }
        public int PerdaPorEntrada { get; set; }
        public string CodRecurso { get; set; }
        public Nullable<double> FatorPeso { get; set; }
        public Nullable<double> FatorComprimento { get; set; }
        public Nullable<double> FatorUnidade { get; set; }
    }
}
